@username = newsomebody4

POST https://localhost:5001/user HTTP/1.1
Content-Type: application/json

{
    "id": "{{username}}",
    "email": "travis.lobert@wellsky.com",
    "firstName": "{{username}}",
    "lastName": "else",
    "terriotyId": "kc",
    "role": "user"
}

###

GET https://localhost:5001/user HTTP/1.1
Authorization: Bearer eyJraWQiOiJ4UTNVeFRucmpPT1V3VnBUdWVkb29zT1d3ZU10QStVMXRrNnJIZFd0aXV3PSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjMTY2NTU3ZS0wNDVkLTRjOGUtYWQyMy1hODM4YTlmYWI4N2QiLCJldmVudF9pZCI6IjcyNWUxNDEyLTA3ZmMtNGE0My1iZjAxLWRjYWI5NjY2NGU1NCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhdXRoX3RpbWUiOjE2MTI4MTU4NjYsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX3dpM2tCT2tvbSIsImV4cCI6MTYxMjgyMzA2NiwiaWF0IjoxNjEyODE1ODY2LCJ2ZXJzaW9uIjoyLCJqdGkiOiIzZmZlOThmOC1iYTQyLTRmMzQtOGIxOC1hYWRmNDRlMjZjNmUiLCJjbGllbnRfaWQiOiIydm1qcmt1ZHQxc3JvY2VwNHAzZjd1ZzVjMCIsInVzZXJuYW1lIjoidHJhdmlzIn0.VS3gzrAzSWFEyoahFH5gmf6owgaXAr9sIGd1z8RR-BHbN0Z83bX7Uqq5f0qfwEAtMfx0Zo8foOyDsTAp_3rTsBu5LMH8EHNsEGwaA-6xwjPdEANflumLZWWfhCzvTk0IivJV7EjzOuYOIkT02JiZDvYmCvluObbWhlFwhCGB1-rk1tF5cRV3kACeeeXtQeKBI3fGIOT_6UCq7X_bjxrwn01i6pLdwk9_Q3k-zUG5lfF4tbarIwPCTfnlvG8JDhvkNNqmnJl5F2093N2mKwe5pwSpkftrSttu1SpMsJx1Iyj89VMkpEmgnluqzR1gpxdiWxfQmz_vSw3b18UDUbFy2Q

###

GET https://localhost:5001/user/{{username}} HTTP/1.1

###

POST https://localhost:5001/user/{{username}}/enable HTTP/1.1

###

POST https://localhost:5001/user/{{username}}/disable HTTP/1.1

###

DELETE https://localhost:5001/user/{{username}} HTTP/1.1