GET https://localhost:5001/whoami HTTP/1.1
Authorization: Bearer eyJraWQiOiJ4UTNVeFRucmpPT1V3VnBUdWVkb29zT1d3ZU10QStVMXRrNnJIZFd0aXV3PSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjMTY2NTU3ZS0wNDVkLTRjOGUtYWQyMy1hODM4YTlmYWI4N2QiLCJldmVudF9pZCI6ImU1YjA1YWNlLTdiYzItNGYwMC1iNjEzLTcwMWMxM2JkODNlMyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhdXRoX3RpbWUiOjE2MTI5NzM5MjQsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX3dpM2tCT2tvbSIsImV4cCI6MTYxMjk4MTEyNCwiaWF0IjoxNjEyOTczOTI0LCJ2ZXJzaW9uIjoyLCJqdGkiOiJjOTFmZGMxZS04NDYyLTQ2OTMtOGM2OC1hMWJlMjI4NjM0ZWIiLCJjbGllbnRfaWQiOiIydm1qcmt1ZHQxc3JvY2VwNHAzZjd1ZzVjMCIsInVzZXJuYW1lIjoidHJhdmlzIn0.rYsu8blU7ksx3BSYPsqqJ-dYN08XS_JaWI2VxS1wtsbTp437EbNVA2YDOHpgLKPXrAcvPuiYpLP8Bh6RKe3jDtDNRst7fAS5eSeQGOzzZWd2ka7lcyHEJntgooIkTVAjC0QqIl5x3I-bjElSBqkdiFaWNoIBFHAA2rGuLNhmnsRJVkhkx_DFN7SqVI7OU56rvVdgySldbmTTUfLr6aLc5VHuU5wd1B09J9xEzAX4wSzYUVLZSnj1I5uUvj4WjYcTVHbnEbGyYhq5hjdDrGDzr-3qtOKtZbqb-CO9ogLWfKh4VG0abX3yGn08wRYqA1Y0w24BLtVvRjGfCuGXMQT6rQ